# Generated by Django 4.2.10 on 2024-03-02 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('atividade_principal', models.CharField(max_length=200, verbose_name='Atividade Principal')),
                ('numero_endereco', models.CharField(max_length=20, verbose_name='Número do Endereço')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('municipio', models.CharField(max_length=100, verbose_name='Município')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
